// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD597IO6Popb-oPkzXi7-GKvhio1dnN7Fc',
    appId: '1:67922882899:web:9b82e581a216dfdb69f1a6',
    messagingSenderId: '67922882899',
    projectId: 'tobeto-flutter-76549',
    authDomain: 'tobeto-flutter-76549.firebaseapp.com',
    storageBucket: 'tobeto-flutter-76549.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92UK0vvSsY0Wa4rRkn6TnCqaLi2djCK4',
    appId: '1:67922882899:android:e67552fe4cc351bd69f1a6',
    messagingSenderId: '67922882899',
    projectId: 'tobeto-flutter-76549',
    storageBucket: 'tobeto-flutter-76549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBA7DmcSKjtbZIqMFsJdh9Kg4KjwEkC8',
    appId: '1:67922882899:ios:07bbeb9f3ce5174c69f1a6',
    messagingSenderId: '67922882899',
    projectId: 'tobeto-flutter-76549',
    storageBucket: 'tobeto-flutter-76549.appspot.com',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBA7DmcSKjtbZIqMFsJdh9Kg4KjwEkC8',
    appId: '1:67922882899:ios:07bbeb9f3ce5174c69f1a6',
    messagingSenderId: '67922882899',
    projectId: 'tobeto-flutter-76549',
    storageBucket: 'tobeto-flutter-76549.appspot.com',
    iosBundleId: 'com.example.firebaseIntro',
  );
}
